# Generated by Django 3.1.7 on 2021-03-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
