# Generated by Django 3.1.7 on 2021-03-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210315_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='types',
            new_name='types_old',
        ),
    ]
