# Generated by Django 3.1.7 on 2021-03-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210315_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(db_table='tasks_types', related_name='tasks_new', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
