# Generated by Django 3.1.7 on 2021-03-15 08:37

from django.db import migrations


def apply_migration(apps, schema_editor):
    Tasks = apps.get_model('webapp', 'Task')
    tasks = Tasks.objects.all()
    for task in tasks:
        task.types.set(task.types_old.all())


def rollback_migrations(apps, schema_editor):
    Tasks = apps.get_model('webapp', 'Task')
    tasks = Tasks.objects.all()
    for task in tasks:
        task.types.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_task_types'),
    ]

    operations = [
        migrations.RunPython(apply_migration, rollback_migrations)
    ]
