# Generated by Django 3.1.7 on 2021-03-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_transactions_types_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='types_old',
        ),
    ]
