# Generated by Django 3.1.7 on 2021-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_task_types_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(db_table='tasks_types', related_name='tasks', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
