# Generated by Django 3.1.7 on 2021-03-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210315_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='statuses',
        ),
    ]
