# Generated by Django 3.1.7 on 2021-03-18 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210318_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Краткое описание'),
        ),
    ]
