# Generated by Django 3.1.7 on 2021-03-18 08:48

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210318_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[webapp.validators.MinLengthValidator(20), webapp.validators.prohibited_word], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=120, validators=[webapp.validators.MinLengthValidator(5), webapp.validators.prohibited_word], verbose_name='Краткое описание'),
        ),
    ]
