# Generated by Django 3.2 on 2021-04-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_or_delete_user', 'Редактировать пользователей')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
