# Generated by Django 3.2 on 2021-04-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_or_delete_user', 'Редактировать пользователей'), ('view_users', 'Просмотр списка пользователей')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
